# Generated by Django 4.1.2 on 2022-10-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_delete_genre_aboutus_description1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='description',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='description2',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
