# Generated by Django 4.1.2 on 2022-10-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_aboutus_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectComplete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happy_clients', models.IntegerField(default=20)),
                ('projects', models.IntegerField(default=20)),
                ('total_hours', models.IntegerField(default=20)),
                ('total_workers', models.IntegerField(default=20)),
            ],
        ),
    ]
