# Generated by Django 4.1.2 on 2022-10-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_projectcomplete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=models.CharField(default=' ', max_length=3000),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='description1',
            field=models.CharField(default=' ', max_length=2000),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='description2',
            field=models.CharField(default=' ', max_length=2000),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='heading1',
            field=models.CharField(default=' ', max_length=2000),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='heading2',
            field=models.CharField(default=' ', max_length=2000),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image_url',
            field=models.CharField(default=' ', max_length=3000),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='li_item_description1',
            field=models.CharField(default=' ', max_length=2000),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='li_item_description2',
            field=models.CharField(default=' ', max_length=2000),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='li_item_heading1',
            field=models.CharField(default=' ', max_length=2000),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='li_item_heading2',
            field=models.CharField(default=' ', max_length=2000),
        ),
    ]
