# Generated by Django 4.1.2 on 2022-10-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_aboutus_description_alter_aboutus_description1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=1000)),
                ('product_description', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
