# Generated by Django 4.1.2 on 2022-10-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image_id',
            field=models.CharField(default='', max_length=500),
        ),
    ]
