# Generated by Django 4.1.2 on 2022-10-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_team_image_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('small_description', models.CharField(max_length=255)),
                ('image_id', models.CharField(max_length=255)),
            ],
        ),
    ]
